# Generated by Django 5.0.6 on 2024-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_roomparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
